### ISSUE TITLE
run testnet tests in CI

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scryptTS-examples#20]
nightly?

Which private key to use? https://github.com/sCrypt-Inc/scryptTS-examples/blob/7789dce463d84bafed4a7c3fd48804f4e3040527/.travis.yml#L14

**Comment by xhliu** [comment]
Let's do weekly and set up a slack hook to channel #travis, as in repo https://github.com/orgs/sCrypt-Inc/ide

**Comment by msinkec** [comment]
Let's just put some key in an env variable and top it up with some testnet coins. Top up once depleted.

**Comment by zhfnjust** [comment]
You can fund its address 'mr1Hwbgb1JFmV94j3vHEPpcQgQDHfD1jvY' , used by ci.
now we can run cron job : https://app.travis-ci.com/github/sCrypt-Inc/scryptTS-examples/jobs/594655448
