### ISSUE TITLE
simplify code

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scryptTS-examples#22]
Remove `types.ts` and put `UTXO` in scrypt-ts directly.
https://github.com/sCrypt-Inc/scryptTS-examples/blob/1bd3c7e461811000df169badb442b0e23c2ab529/src/types.ts#L3

Remove all bsv prefixes, looking redundant. Maybe re-export in scrypt-ts directly.
https://github.com/sCrypt-Inc/scryptTS-examples/blob/1bd3c7e461811000df169badb442b0e23c2ab529/src/contracts/p2pkh.ts#L44-L48

**Comment by msinkec** [comment]
`UTXO` is already directly exported in `scrypt-ts`.

**Comment by xhliu** [comment]
bsv prefixes are still there. @msinkec

**Comment by xhliu** [comment]
![Image](https://user-images.githubusercontent.com/1017252/217157548-331aed3c-74ae-4010-8fd6-7a1a6067b90b.png)

**Comment by msinkec** [comment]
I now import from the 'bsv' module explicitly. I think it's better to do so  opposed to having everything a first class citizen to avoid confusion like this:

```ts
import { PrivKey, PrivateKey } from 'scrypt-ts'
```

which would be horrible.

However what I'd need is to import from the submodule directly, like this:

```ts
import { PrivateKey } from 'scrypt-ts/bsv'
```

I think this is not doable ATM, so here's an issue to track this: https://github.com/sCrypt-Inc/scrypt-ts/issues/191

Also the PR for scryptTS-examples: https://github.com/sCrypt-Inc/scryptTS-examples/pull/32
