### ISSUE TITLE
add readonly to all @prop(false)

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scryptTS-examples#35]
since it is almost always immutable. Also update all scryptTS repos: scrypt-ts, docs, lib.

```
@prop()
  readonly x: bigint
```

**Comment by msinkec** [comment]
Done in scryptTS-examples: https://github.com/sCrypt-Inc/scryptTS-examples/commit/85919f1907bbb271182b3a405eb8a16906e898d7

**Comment by msinkec** [comment]
Done in docs: https://github.com/sCrypt-Inc/scryptTS-docs/commit/46bc4b6b18b9fddeef59f7b8d74610126d5c898a

**Comment by msinkec** [comment]
And it's already all readonly in scrypt-ts-lib. Closing this.
