### ISSUE TITLE
add examples to customize tx

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scryptTS-examples#51]
https://scrypt.io/scrypt-ts/how-to-build-a-contract-tx

**Comment by gitzhou** [comment]
commit cf3ea45a1100a8f3613371d044f892e0b66e3605

- [customized deployment](https://github.com/sCrypt-Inc/scryptTS-examples/blob/cf3ea45a11/src/contracts/auction.ts#L100-L127)
- [customized call](https://github.com/sCrypt-Inc/scryptTS-examples/blob/cf3ea45a11/src/contracts/auction.ts#L129-L178)
