### ISSUE TITLE
Test SmartContract `AccumulatorMultiSig` on testnet failed

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scryptTS-examples#57]
https://app.travis-ci.com/github/sCrypt-Inc/scryptTS-examples/jobs/597307884

![image](https://user-images.githubusercontent.com/1017252/222993626-87b383ed-bacb-4513-9adb-c2fc9c20c251.png)

**Comment by gitzhou** [comment]
re-run to fix

**Comment by zhfnjust** [comment]
Fixed in https://github.com/sCrypt-Inc/scryptTS-examples/commit/b17577885d340e10ef3efae99149f89b1f929663

don't run testnet parallelly
