### ISSUE TITLE
add more info README

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scryptTS-examples#7]
- how to run test & testnet
- how to config a private key, e.g., in .env. First generate it and then fund it via a faucet.

**Comment by xhliu** [comment]
Not clear to users how to proceed https://scryptworkspace.slack.com/archives/CLSHPUZC3/p1672776173866979

**Comment by gitzhou** [comment]
<img width="744" alt="CleanShot-2023-01-09-16-40-06" src="https://user-images.githubusercontent.com/1585505/211268383-b422cf05-b0c2-442c-b1db-43a97505a606.png">

**Comment by xhliu** [comment]
@gitzhou
